import type {Metadata} from "next"; // Импорт типа Metadata из Next.js для определения метаданных страницы
import {Geist, Geist_Mono} from "next/font/google"; // Импорт функций для работы с Google Fonts из Next.js
import "./globals.css"; // Импорт глобальных стилей CSS из файла globals.css

// Конфигурация шрифта Geist Sans от Vercel Fonts
const geistSans = Geist({
    // Определение CSS переменной для шрифта Geist Sans
    variable: "--font-geist-sans",
    // Указание подмножества символов (только латиница для оптимизации)
    subsets: ["latin"],
});

// Конфигурация шрифта Geist Mono от Vercel Fonts (моноширинный шрифт)
const geistMono = Geist_Mono({
    // Определение CSS переменной для шрифта Geist Mono
    variable: "--font-geist-mono",
    // Указание подмножества символов (только латиница)
    subsets: ["latin"],
});

// Определение метаданных для всего приложения (корневого layout)
export const metadata: Metadata = {
    // Заголовок по умолчанию для всех страниц (измените на название вашего приложения)
    title: "Create Next App",
    // Описание по умолчанию (измените на описание вашего приложения)
    description: "Generated by create next app",
};

// RootLayout - корневой Layout компонент, оборачивает все страницы приложения.
export default function RootLayout(
    {
        // children prop - представляет собой содержимое вложенных страниц
        children,
    }: Readonly<{
        // Типизация children как ReactNode (любой renderable React контент)
        children: React.ReactNode;
    }>) {
    return (
        // Корневой HTML-тег, lang="en" указывает язык сайта (английский)
        <html lang="en">
        {/* Тег body - основное содержимое страницы */}
        <body
            // Применение классов CSS к body: шрифты Geist и antialiasing
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        {/* Рендеринг children - содержимое страниц будет вставлено сюда */}
        {children}
        </body>
        </html>
    );
}